### ISSUE TITLE
Jump to init() or method of form

### ISSUE THREAD

**Issue by tomkn** [VFPX/GoToDefinition#23]
Hello,

what a great tool. THANKS A LOT.

I wonder whether its possible to open .init in editor or jump to documentview of a form when called with do form xxx is recognized.
That would be great to look for optional parameters needed there.

like do form adress_input opens the form adress_input and opens its .init

Best regards
Tom

**Comment by Jimrnelson** [comment]
@tomkn 

You're welcome, Tom,  I'm very glad to find GTD of value.

As for your request, I'll have to give that some thought.  

Having GTD open a form's Init automatically seems like a very special case, one that may appeal to you but not necessarily to others.  The default behavior is to open the form as if it were entered from the Command Window:

    Modify Form xxx

For me, personally, I might like this on occasion but in most cases I would think that opening the Init would just get in the way.

My initial take on this is that the best way to implement your request would have to be providing some optional way for you to achieve what you wanted that would not necessarily impact any others.

**Comment by tomkn** [comment]
Thanks for the fast response and again for this tool.

I understand.
And implementing adress_input,init()  similar to thisform.init() makes no sense, too much to type.

I will try  to assign documentview to a hotkey, maybe with autohotkey (In german version ALT+D opens Menu Datei (File) instead of Dokumentenansicht (both have ALT+D)

BR
Tom

**Comment by Jimrnelson** [comment]
@tomkn 

Tom --

You could also create a private Thor tool, with this single line of code:

    Activate Window Document

and assign a hot key to it.
